FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3-pip python3-dev \
    libglib2.0-0 libsm6 libxrender1 libxext6 libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY server/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY server /app

EXPOSE 5000

CMD ["python3", "main.py"]
